name: 'ecommerce_olist'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_olist'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_olist:
    bronze:
      +materialized: ephemeral
    silver:
      +materialized: ephemeral
    gold:
      +materialized: ephemeral